export const QuotaMaximumAudioFileLengthInSeconds=14400;
export const QuotaMaximumAudioFileSizeInBytes=2000000000;
export const QuotaMaximumSizeOfACustomVocabularyInKB=50;
export const QuotaMaximumLengthOfACustomVocabularyPhraseInCharacters=256;
export const QuotaMaximumSizeOfAVocabularyFilter=50;
export const QuotaMaximumNumberOfVocabularyFilters=100;
export const QuotaNumberOfDaysThatJobRecordsAreRetained=90;
export const QuotaNumberOfChannelsForChannelIdentification=2;
export const QuotaMinimumAudioFileDurationInMilliseconds=500;

export const COUNTRIES= [ 
  {"value": "US","text":"United States of America"},
  {"value":"GB","text":"United Kingdom of Great Britain and Northern Ireland"},
  {"value":"FR","text":"France"},
  {"value":"ES","text":"Spain"},
  {"value":"AD","text":"Andorra"},
  {"value":"AE","text":"United Arab Emirates"},
  {"value":"AF","text":"Afghanistan"},
  {"value":"AG","text":"Antigua and Barbuda"},
  {"value":"AI","text":"Anguilla"},
  {"value":"AL","text":"Albania"},
  {"value":"AM","text":"Armenia"},
  {"value":"AO","text":"Angola"},
  {"value":"AQ","text":"Antarctica"},
  {"value":"AR","text":"Argentina"},
  {"value":"AS","text":"American Samoa"},
  {"value":"AT","text":"Austria"},
  {"value":"AU","text":"Australia"},
  {"value":"AW","text":"Aruba"},
  {"value":"AX","text":"Åland Islands"},
  {"value":"AZ","text":"Azerbaijan"},
  {"value":"BA","text":"Bosnia and Herzegovina"},
  {"value":"BB","text":"Barbados"},
  {"value":"BD","text":"Bangladesh"},
  {"value":"BE","text":"Belgium"},
  {"value":"BF","text":"Burkina Faso"},
  {"value":"BG","text":"Bulgaria"},
  {"value":"BH","text":"Bahrain"},
  {"value":"BI","text":"Burundi"},
  {"value":"BJ","text":"Benin"},
  {"value":"BL","text":"Saint Barthélemy"},
  {"value":"BM","text":"Bermuda"},
  {"value":"BN","text":"Brunei Darussalam"},
  {"value":"BO","text":"Bolivia, Plurinational State of"},
  {"value":"BQ","text":"Bonaire, Sint Eustatius and Saba"},
  {"value":"BR","text":"Brazil"},
  {"value":"BS","text":"Bahamas"},
  {"value":"BT","text":"Bhutan"},
  {"value":"BV","text":"Bouvet Island"},
  {"value":"BW","text":"Botswana"},
  {"value":"BY","text":"Belarus"},
  {"value":"BZ","text":"Belize"},
  {"value":"CA","text":"Canada"},
  {"value":"CC","text":"Cocos (Keeling) Islands"},
  {"value":"CD","text":"Congo, Democratic Republic of the"},
  {"value":"CF","text":"Central African Republic"},
  {"value":"CG","text":"Congo"},
  {"value":"CH","text":"Switzerland"},
  {"value":"CI","text":"Côte d'Ivoire"},
  {"value":"CK","text":"Cook Islands"},
  {"value":"CL","text":"Chile"},
  {"value":"CM","text":"Cameroon"},
  {"value":"CN","text":"China"},
  {"value":"CO","text":"Colombia"},
  {"value":"CR","text":"Costa Rica"},
  {"value":"CU","text":"Cuba"},
  {"value":"CV","text":"Cabo Verde"},
  {"value":"CW","text":"Curaçao"},
  {"value":"CX","text":"Christmas Island"},
  {"value":"CY","text":"Cyprus"},
  {"value":"CZ","text":"Czechia"},
  {"value":"DE","text":"Germany"},
  {"value":"DJ","text":"Djibouti"},
  {"value":"DK","text":"Denmark"},
  {"value":"DM","text":"Dominica"},
  {"value":"DO","text":"Dominican Republic"},
  {"value":"DZ","text":"Algeria"},
  {"value":"EC","text":"Ecuador"},
  {"value":"EE","text":"Estonia"},
  {"value":"EG","text":"Egypt"},
  {"value":"EH","text":"Western Sahara"},
  {"value":"ER","text":"Eritrea"},
  {"value":"ET","text":"Ethiopia"},
  {"value":"FI","text":"Finland"},
  {"value":"FJ","text":"Fiji"},
  {"value":"FK","text":"Falkland Islands (Malvinas)"},
  {"value":"FM","text":"Micronesia, Federated States of"},
  {"value":"FO","text":"Faroe Islands"},
  {"value":"GA","text":"Gabon"},
  {"value":"GD","text":"Grenada"},
  {"value":"GE","text":"Georgia"},
  {"value":"GF","text":"French Guiana"},
  {"value":"GG","text":"Guernsey"},
  {"value":"GH","text":"Ghana"},
  {"value":"GI","text":"Gibraltar"},
  {"value":"GL","text":"Greenland"},
  {"value":"GM","text":"Gambia"},
  {"value":"GN","text":"Guinea"},
  {"value":"GP","text":"Guadeloupe"},
  {"value":"GQ","text":"Equatorial Guinea"},
  {"value":"GR","text":"Greece"},
  {"value":"GS","text":"South Georgia and the South Sandwich Islands"},
  {"value":"GT","text":"Guatemala"},
  {"value":"GU","text":"Guam"},
  {"value":"GW","text":"Guinea-Bissau"},
  {"value":"GY","text":"Guyana"},
  {"value":"HK","text":"Hong Kong"},
  {"value":"HM","text":"Heard Island and McDonald Islands"},
  {"value":"HN","text":"Honduras"},
  {"value":"HR","text":"Croatia"},
  {"value":"HT","text":"Haiti"},
  {"value":"HU","text":"Hungary"},
  {"value":"ID","text":"Indonesia"},
  {"value":"IE","text":"Ireland"},
  {"value":"IL","text":"Israel"},
  {"value":"IM","text":"Isle of Man"},
  {"value":"IN","text":"India"},
  {"value":"IO","text":"British Indian Ocean Territory"},
  {"value":"IQ","text":"Iraq"},
  {"value":"IR","text":"Iran, Islamic Republic of"},
  {"value":"IS","text":"Iceland"},
  {"value":"IT","text":"Italy"},
  {"value":"JE","text":"Jersey"},
  {"value":"JM","text":"Jamaica"},
  {"value":"JO","text":"Jordan"},
  {"value":"JP","text":"Japan"},
  {"value":"KE","text":"Kenya"},
  {"value":"KG","text":"Kyrgyzstan"},
  {"value":"KH","text":"Cambodia"},
  {"value":"KI","text":"Kiribati"},
  {"value":"KM","text":"Comoros"},
  {"value":"KN","text":"Saint Kitts and Nevis"},
  {"value":"KP","text":"Korea, Democratic People's Republic of"},
  {"value":"KR","text":"Korea, Republic of"},
  {"value":"KW","text":"Kuwait"},
  {"value":"KY","text":"Cayman Islands"},
  {"value":"KZ","text":"Kazakhstan"},
  {"value":"LA","text":"Lao People's Democratic Republic"},
  {"value":"LB","text":"Lebanon"},
  {"value":"LC","text":"Saint Lucia"},
  {"value":"LI","text":"Liechtenstein"},
  {"value":"LK","text":"Sri Lanka"},
  {"value":"LR","text":"Liberia"},
  {"value":"LS","text":"Lesotho"},
  {"value":"LT","text":"Lithuania"},
  {"value":"LU","text":"Luxembourg"},
  {"value":"LV","text":"Latvia"},
  {"value":"LY","text":"Libya"},
  {"value":"MA","text":"Morocco"},
  {"value":"MC","text":"Monaco"},
  {"value":"MD","text":"Moldova, Republic of"},
  {"value":"ME","text":"Montenegro"},
  {"value":"MF","text":"Saint Martin, (French part)"},
  {"value":"MG","text":"Madagascar"},
  {"value":"MH","text":"Marshall Islands"},
  {"value":"MK","text":"North Macedonia"},
  {"value":"ML","text":"Mali"},
  {"value":"MM","text":"Myanmar"},
  {"value":"MN","text":"Mongolia"},
  {"value":"MO","text":"Macao"},
  {"value":"MP","text":"Northern Mariana Islands"},
  {"value":"MQ","text":"Martinique"},
  {"value":"MR","text":"Mauritania"},
  {"value":"MS","text":"Montserrat"},
  {"value":"MT","text":"Malta"},
  {"value":"MU","text":"Mauritius"},
  {"value":"MV","text":"Maldives"},
  {"value":"MW","text":"Malawi"},
  {"value":"MX","text":"Mexico"},
  {"value":"MY","text":"Malaysia"},
  {"value":"MZ","text":"Mozambique"},
  {"value":"NA","text":"Namibia"},
  {"value":"NC","text":"New Caledonia"},
  {"value":"NE","text":"Niger"},
  {"value":"NF","text":"Norfolk Island"},
  {"value":"NG","text":"Nigeria"},
  {"value":"NI","text":"Nicaragua"},
  {"value":"NL","text":"Netherlands"},
  {"value":"NO","text":"Norway"},
  {"value":"NP","text":"Nepal"},
  {"value":"NR","text":"Nauru"},
  {"value":"NU","text":"Niue"},
  {"value":"NZ","text":"New Zealand"},
  {"value":"OM","text":"Oman"},
  {"value":"PA","text":"Panama"},
  {"value":"PE","text":"Peru"},
  {"value":"PF","text":"French Polynesia"},
  {"value":"PG","text":"Papua New Guinea"},
  {"value":"PH","text":"Philippines"},
  {"value":"PK","text":"Pakistan"},
  {"value":"PL","text":"Poland"},
  {"value":"PM","text":"Saint Pierre and Miquelon"},
  {"value":"PN","text":"Pitcairn"},
  {"value":"PR","text":"Puerto Rico"},
  {"value":"PS","text":"Palestine, State of"},
  {"value":"PT","text":"Portugal"},
  {"value":"PW","text":"Palau"},
  {"value":"PY","text":"Paraguay"},
  {"value":"QA","text":"Qatar"},
  {"value":"RE","text":"Réunion"},
  {"value":"RO","text":"Romania"},
  {"value":"RS","text":"Serbia"},
  {"value":"RU","text":"Russian Federation"},
  {"value":"RW","text":"Rwanda"},
  {"value":"SA","text":"Saudi Arabia"},
  {"value":"SB","text":"Solomon Islands"},
  {"value":"SC","text":"Seychelles"},
  {"value":"SD","text":"Sudan"},
  {"value":"SE","text":"Sweden"},
  {"value":"SG","text":"Singapore"},
  {"value":"SH","text":"Saint Helena, Ascension and Tristan da Cunha"},
  {"value":"SI","text":"Slovenia"},
  {"value":"SJ","text":"Svalbard and Jan Mayen"},
  {"value":"SK","text":"Slovakia"},
  {"value":"SL","text":"Sierra Leone"},
  {"value":"SM","text":"San Marino"},
  {"value":"SN","text":"Senegal"},
  {"value":"SO","text":"Somalia"},
  {"value":"SR","text":"Suriname"},
  {"value":"SS","text":"South Sudan"},
  {"value":"ST","text":"Sao Tome and Principe"},
  {"value":"SV","text":"El Salvador"},
  {"value":"SX","text":"Sint Maarten, (Dutch part)"},
  {"value":"SY","text":"Syrian Arab Republic"},
  {"value":"SZ","text":"Eswatini"},
  {"value":"TC","text":"Turks and Caicos Islands"},
  {"value":"TD","text":"Chad"},
  {"value":"TF","text":"French Southern Territories"},
  {"value":"TG","text":"Togo"},
  {"value":"TH","text":"Thailand"},
  {"value":"TJ","text":"Tajikistan"},
  {"value":"TK","text":"Tokelau"},
  {"value":"TL","text":"Timor-Leste"},
  {"value":"TM","text":"Turkmenistan"},
  {"value":"TN","text":"Tunisia"},
  {"value":"TO","text":"Tonga"},
  {"value":"TR","text":"Turkey"},
  {"value":"TT","text":"Trinidad and Tobago"},
  {"value":"TV","text":"Tuvalu"},
  {"value":"TW","text":"Taiwan, Province of China"},
  {"value":"TZ","text":"Tanzania, United Republic of"},
  {"value":"UA","text":"Ukraine"},
  {"value":"UG","text":"Uganda"},
  {"value":"UM","text":"United States Minor Outlying Islands"},
  {"value":"UY","text":"Uruguay"},
  {"value":"UZ","text":"Uzbekistan"},
  {"value":"VA","text":"Holy See"},
  {"value":"VC","text":"Saint Vincent and the Grenadines"},
  {"value":"VE","text":"Venezuela, Bolivarian Republic of"},
  {"value":"VG","text":"Virgin Islands, British"},
  {"value":"VI","text":"Virgin Islands, U.S."},
  {"value":"VN","text":"Viet Nam"},
  {"value":"VU","text":"Vanuatu"},
  {"value":"WF","text":"Wallis and Futuna"},
  {"value":"WS","text":"Samoa"},
  {"value":"YE","text":"Yemen"},
  {"value":"YT","text":"Mayotte"},
  {"value":"ZA","text":"South Africa"},
  {"value":"ZM","text":"Zambia"},
  {"value":"ZW","text":"Zimbabwe"},
];

export const PRICING= [
        {"id": 1,"priceperhour": 10,"hourmin": 0,"hourmax": 24, discountPercentage:0},
        {"id": 2,"priceperhour": 9,"hourmin": 25,"hourmax": 49, discountPercentage:10},
        {"id": 3,"priceperhour": 8,"hourmin": 50,"hourmax": 100, discountPercentage:20},
      ];
//export const AUDIO_VIDEO_FILE_EXTENSIONS= '.WEBM, .MPG, .MP2, .MPEG, .MPE, .MPV, .OGG, .MP4, .M4P, .M4V, .AVI, .WMV, .MOV, .QT, .FLV, .SWF, AVCHD';
export const AUDIO_VIDEO_FILE_EXTENSIONS_MimeTypes= 
[
  {"id":1, "description":"audio file",                        "mimeType": 'audio/basic', "extension":'.au'},
  {"id":2, "description":"sound file",                        "mimeType": 'audio/basic', "extension":'.snd'},
  {"id":3, "description":"midi file",                         "mimeType": 'audio/mid', "extension":'.mid'},
  {"id":4, "description":"media processing server studio",    "mimeType": 'audio/mid', "extension":'	.rmi'},
  {"id":5, "description":"MP3 file",                          "mimeType": 'audio/mpeg', "extension":'.mp3'},
  {"id":6, "description":"audio interchange file format",     "mimeType": 'audio/x-aiff', "extension":'.aif'},
  {"id":7, "description":"compressed audio interchange file", "mimeType": 'audio/x-aiff', "extension":'.aifc'},
  {"id":8, "description":"audio interchange file format",     "mimeType": 'audio/x-aiff', "extension":'.aiff'},
  {"id":9, "description":"media playlist file",               "mimeType": 'audio/x-mpegurl', "extension":'.m3u'},
  {"id":10, "description":"Real Audio file",                  "mimeType": 'audio/x-pn-realaudio', "extension":'.ra'},
  {"id":11, "description":"Real Audio metadata file",         "mimeType": 'audio/x-pn-realaudio', "extension":'.ram'},
  {"id":12, "description":"WAVE audio file",                  "mimeType": 'audio/x-wav', "extension":'.wav'},

  {"id":13, "description":"MPEG-2 audio file",                "mimeType": 'video/mpeg', "extension":'.mp2'},
  {"id":14, "description":"MPEG-2 audio file",                "mimeType": 'video/mpeg', "extension":'.mpa'},
  {"id":15, "description":"MPEG movie file",                   "mimeType": 'video/mpeg', "extension":'.mpe'},
  {"id":16, "description":"MPEG movie file",                  "mimeType": 'video/mpeg', "extension":'.mpeg'},
  {"id":17, "description":"MPEG movie file",                  "mimeType": 'video/mpeg', "extension":'.mpg'},
  {"id":18, "description":"MPEG-2 video stream",              "mimeType": 'video/mpeg', "extension":'.mpv2'},
  {"id":19, "description":"MPEG-4",                           "mimeType": 'video/mp4', "extension":'.mp4'},
  {"id":20, "description":"Apple QuickTime movie",            "mimeType": 'video/quicktime', "extension":'.mov'},
  {"id":21, "description":"Apple QuickTime movie",            "mimeType": 'video/quicktime', "extension":'.qt'},
  {"id":22, "description":"Logos library system file",        "mimeType": 'video/x-la-asf', "extension":'.lsf'},
  {"id":23, "description":"streaming media shortcut",         "mimeType": 'video/x-la-asf', "extension":'.lsx'},
  {"id":24, "description":"advanced systems format file",     "mimeType": 'video/x-ms-asf', "extension":'.asf'},
  {"id":25, "description":"ActionScript remote document",     "mimeType": 'video/x-ms-asf', "extension":'.asr'},
  {"id":26, "description":"Microsoft ASF redirector file",    "mimeType": 'video/x-ms-asf', "extension":'.asx'},
  {"id":27, "description":"audio video interleave file",      "mimeType": 'video/x-msvideo', "extension":'.avi'},
  {"id":28, "description":"Apple QuickTime movie",            "mimeType": 'video/x-sgi-movie', "extension":'.movie'},
];

export const FILE_SOURCES= [
    { text: 'Your device', id: '1', category: 'Local sources'  },
    { text: 'Public links" subtitle="Eg: Youtube, Instagram etc', id: '2', category: 'Online sources'  },
    { text: 'Google drive', id: '3' , category: 'Online sources' },
    { text: 'Dropbox', id: '4', category: 'Online sources'  },
    { text: 'Your Vimeo channel', id: '5', category: 'Online sources'  },
    { text: 'Your Youtube channel', id: '6', category: 'Online sources'  },
    { text: 'Wistia', id: '7', category: 'Online sources' },
  ];
  
//AWS transcribe supported languages
export const FILE_LANGUAGES =[
  {Category: 'Top languages', Text: 'British English',        Id: 'en-GB'},
  {Category: 'Top languages', Text: 'US English',             Id: 'en-US'},
  {Category: 'Top languages', Text: 'Spanish',                Id: 'es-ES'},
  {Category: 'Top languages', Text: 'French',                 Id: 'fr-FR'},
  
  {Category: 'All languages', Text: 'Australian English',     Id: 'en-AU'},
  {Category: 'All languages', Text: 'Indian English',         Id: 'en-IN'},
  {Category: 'All languages', Text: 'Irish English',          Id: 'en-IE'},
  {Category: 'All languages', Text: 'Scottish English',       Id: 'en-AB'},
  {Category: 'All languages', Text: 'Welsh English',          Id: 'en-WL'},
  {Category: 'All languages', Text: 'US Spanish',             Id: 'es-US'},
  {Category: 'All languages', Text: 'Canadian French',        Id: 'fr-CA'},
  
  {Category: 'All languages', Text: 'Gulf Arabic',                Id: 'ar-AE'},
  {Category: 'All languages', Text: 'Modern Standard Arabic',     Id: 'ar-SA'},
  {Category: 'All languages', Text: 'Chinese Mandarin - Mainland',Id: 'zh-CN'},
  {Category: 'All languages', Text: 'Dutch',                      Id: 'nl-NL'},
  {Category: 'All languages', Text: 'Farsi',                      Id: 'fa-IR'},
  {Category: 'All languages', Text: 'German',                     Id: 'de-DE'},
  {Category: 'All languages', Text: 'Swiss German',               Id: 'de-CH'},
  {Category: 'All languages', Text: 'Hebrew',                     Id: 'he-IL'},
  {Category: 'All languages', Text: 'Indian Hindi',               Id: 'hi-IN'},
  {Category: 'All languages', Text: 'Indonesian',                 Id: 'id-ID'},
  {Category: 'All languages', Text: 'Italian',                    Id: 'it-IT'},
  {Category: 'All languages', Text: 'Japanese',                   Id: 'ja-JP'},
  {Category: 'All languages', Text: 'Korean',                     Id: 'ko-KR'},
  {Category: 'All languages', Text: 'Malay',                      Id: 'ms-MY'},
  {Category: 'All languages', Text: 'Portuguese',                 Id: 'pt-PT'},
  {Category: 'All languages', Text: 'Brazilian Portuguese',       Id: 'pt-BR'},
  {Category: 'All languages', Text: 'Russian',                    Id: 'ru-RU'},
  {Category: 'All languages', Text: 'Tamil',                      Id: 'ta-IN'},
  {Category: 'All languages', Text: 'Telugu',                     Id: 'te-IN'},
  {Category: 'All languages', Text: 'Turkish',                    Id: 'tr-TR'},
    ];